development:
  adapter: async

test:
  adapter: test

production:
  # adapter: radis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: syuwakai_production
  adapter: async
